### PR TITLE
issue resolved for making card horizontal

### PR DESCRIPTION
**Pull request by ritikakhandelwal-17**
I have made a division in which all cards are stored and made it flex box , so they become horizontal an d using media query for width less than 600px made flex alignment as column so it is responsive. Also set a height for images in card so that all look good.

### CODE REVIEW

**Review by liambrewster — APPROVED** [review]
Looks Like a good solution, maybe they will accept your PR soon

**Comment by annanyadas** [comment]
hey @ritikakhandelwal-17  nice to have you on this issue . i dont think media queries is required as flex wrap property can cover that. Thank you

**Comment by ritikakhandelwal-17** [comment]
@annanyadas Thank you for the idea . I have implemented it and made a new pull request that can be merged

**Comment by annanyadas** [comment]
I viewed it . I will merge it . glad to have you . Thank you

**Pull request merged**
